import type { DailyTask, Exam, MistakeRecord, Subject, Topic, UserProfile } from "@/types/study";

export const defaultProfile: UserProfile = {
  name: "Öğrenci",
  targetDepartment: "Hedef Belirle",
  targetUniversity: "",
  targetRank: 10000,
  examType: "TYT+AYT",
  dayCount: 1,
  totalDays: 365,
  streakDays: 0,
  totalQuestionsSolved: 0,
  totalHoursStudied: 0,
  examTargetNet: 85,
};

export const todayTasks: DailyTask[] = [];

export const subjects: Subject[] = [
  {
    id: "turkce",
    name: "TYT Türkçe",
    examType: "TYT",
    topicCount: 15,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "tyt-matematik",
    name: "TYT Matematik",
    examType: "TYT",
    topicCount: 25,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "geometri",
    name: "Geometri",
    examType: "TYT",
    topicCount: 14,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "tyt-fizik",
    name: "TYT Fizik",
    examType: "TYT",
    topicCount: 11,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "tyt-kimya",
    name: "TYT Kimya",
    examType: "TYT",
    topicCount: 9,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "tyt-biyoloji",
    name: "TYT Biyoloji",
    examType: "TYT",
    topicCount: 9,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "tyt-sosyal",
    name: "TYT Tarih & Coğrafya & Felsefe",
    examType: "TYT",
    topicCount: 12,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "ayt-matematik",
    name: "AYT Matematik",
    examType: "AYT",
    topicCount: 15,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "ayt-fizik",
    name: "AYT Fizik",
    examType: "AYT",
    topicCount: 15,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "ayt-kimya",
    name: "AYT Kimya",
    examType: "AYT",
    topicCount: 12,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "ayt-biyoloji",
    name: "AYT Biyoloji",
    examType: "AYT",
    topicCount: 13,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
  {
    id: "ayt-edebiyat",
    name: "AYT Edebiyat",
    examType: "AYT",
    topicCount: 11,
    completedTopics: 0,
    progress: 0,
    weeklyQuestions: 0,
  },
];

export const allTopics: Topic[] = [
  // ==================== TYT TÜRKÇE (15 Konu) ====================
  { id: "tr-sozcukte-anlam", subjectId: "turkce", name: "Sözcükte ve Söz Öbeklerinde Anlam", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-cumlede-anlam", subjectId: "turkce", name: "Cümlede Anlam ve Kavramlar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-paragrafta-anlam", subjectId: "turkce", name: "Paragrafta Anlam ve Yapı", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-paragrafta-ana-fikir", subjectId: "turkce", name: "Paragrafta Ana Düşünce & Yardımcı Düşünceler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-anlatim-teknikleri", subjectId: "turkce", name: "Anlatım Teknikleri ve Düşünceyi Geliştirme Yolları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-ses-bilgisi", subjectId: "turkce", name: "Ses Bilgisi (Ses Olayları)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-yazim-kurallari", subjectId: "turkce", name: "Yazım Kuralları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-noktalama-isaretleri", subjectId: "turkce", name: "Noktalama İşaretleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-sozcukte-yapi", subjectId: "turkce", name: "Sözcükte Yapı ve Ekler (Kök-Gövde)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-sozcuk-turleri", subjectId: "turkce", name: "İsim, Sıfat, Zamir, Zarf", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-edat-baglac-unlem", subjectId: "turkce", name: "Edat, Bağlaç ve Ünlem", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-fiiller-ekfiil-fiilimsi", subjectId: "turkce", name: "Fiiller, Ek Fiil ve Fiilimsiler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-fiilde-cati", subjectId: "turkce", name: "Fiilde Çatı", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-cumlenin-ogeleri", subjectId: "turkce", name: "Cümlenin Ögeleri ve Cümle Türleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "tr-anlatim-bozukluklari", subjectId: "turkce", name: "Anlatım Bozuklukları", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== TYT MATEMATİK (25 Konu) ====================
  { id: "mat-temel-kavramlar", subjectId: "tyt-matematik", name: "Temel Kavramlar & Sayı Kümeleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-sayi-basamaklari", subjectId: "tyt-matematik", name: "Sayı Basamakları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-bolme-bolunebilme", subjectId: "tyt-matematik", name: "Bölme ve Bölünebilme Kuralları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-ebob-ekok", subjectId: "tyt-matematik", name: "Asal Çarpanlar ve EBOB - EKOK", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-rasyonel-sayilar", subjectId: "tyt-matematik", name: "Rasyonel ve Ondalık Sayılar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-basit-esitsizlikler", subjectId: "tyt-matematik", name: "Basit Eşitsizlikler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-mutlak-deger", subjectId: "tyt-matematik", name: "Mutlak Değer", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-uslu-sayilar", subjectId: "tyt-matematik", name: "Üslü İfadeler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-koklu-sayilar", subjectId: "tyt-matematik", name: "Köklü İfadeler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-carpanlara-ayirma", subjectId: "tyt-matematik", name: "Çarpanlara Ayırma ve Özdeşlikler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-oran-oranti", subjectId: "tyt-matematik", name: "Oran ve Orantı", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-denklem-cozme", subjectId: "tyt-matematik", name: "Birinci Dereceden Denklem Çözme", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-sayi-kesir-problemleri", subjectId: "tyt-matematik", name: "Sayı ve Kesir Problemleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-yas-problemleri", subjectId: "tyt-matematik", name: "Yaş Problemleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-hareket-problemleri", subjectId: "tyt-matematik", name: "Hız ve Hareket Problemleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-yuzde-kar-zarar", subjectId: "tyt-matematik", name: "Yüzde, Kâr-Zarar ve İskonto Problemleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-karisim-problemleri", subjectId: "tyt-matematik", name: "Karışım Problemleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-grafik-problemleri", subjectId: "tyt-matematik", name: "Grafik ve Tablo Yorumlama", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-kumeler", subjectId: "tyt-matematik", name: "Kümeler ve Kartezyen Çarpım", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-mantik", subjectId: "tyt-matematik", name: "Mantık", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-fonksiyonlar", subjectId: "tyt-matematik", name: "Fonksiyonlar (Tanım, Grafikler, Bileşke)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-polinomlar", subjectId: "tyt-matematik", name: "Polinomlar ve Bölme", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-permutasyon-kombinasyon", subjectId: "tyt-matematik", name: "Sayma, Permütasyon ve Kombinasyon", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-olasilik", subjectId: "tyt-matematik", name: "Olasılık", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "mat-istatistik", subjectId: "tyt-matematik", name: "İstatistik (Mod, Medyan, Standart Sapma)", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== GEOMETRİ (14 Konu) ====================
  { id: "geo-dogruda-ucgende-acilar", subjectId: "geometri", name: "Doğruda ve Üçgende Açılar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-ozel-ucgenler", subjectId: "geometri", name: "Özel Üçgenler (Dik, İkizkenar, Eşkenar)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-aciortay-kenarortay", subjectId: "geometri", name: "Üçgende Açıortay ve Kenarortay", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-eslik-benzerlik", subjectId: "geometri", name: "Üçgende Eşlik ve Benzerlik", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-ucgende-alan", subjectId: "geometri", name: "Üçgende Alan Bağıntıları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-cokgenler-dortgenler", subjectId: "geometri", name: "Çokgenler ve Dörtgenler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-yamuk-paralelkenar", subjectId: "geometri", name: "Yamuk ve Paralelkenar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-eskenar-dortgen-deltoid", subjectId: "geometri", name: "Eşkenar Dörtgen ve Deltoid", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-dikdortgen-kare", subjectId: "geometri", name: "Dikdörtgen ve Kare", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-cemberde-acilar", subjectId: "geometri", name: "Çemberde Açılar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-cemberde-uzunluk-dairede-alan", subjectId: "geometri", name: "Çemberde Uzunluk ve Dairede Alan", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-nokta-dogru-analitigi", subjectId: "geometri", name: "Noktanın ve Doğrunun Analitiği", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-kati-cisimler", subjectId: "geometri", name: "Katı Cisimler (Prizma, Piramit, Koni, Küre)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "geo-cemberin-analitigi", subjectId: "geometri", name: "Çemberin Analitik İncelenmesi", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== TYT FİZİK (11 Konu) ====================
  { id: "fiz-fizik-bilimine-giris", subjectId: "tyt-fizik", name: "Fizik Bilimine Giriş", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-madde-ozellikleri", subjectId: "tyt-fizik", name: "Madde ve Özellikleri (Özkütle, Yüzey Gerilimi)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-hareket-kuvvet", subjectId: "tyt-fizik", name: "Kuvvet ve Hareket", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-is-guc-enerji", subjectId: "tyt-fizik", name: "İş, Güç ve Enerji", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-isi-sicaklik-genlesme", subjectId: "tyt-fizik", name: "Isı, Sıcaklık ve Genleşme", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-elektrostatik", subjectId: "tyt-fizik", name: "Elektrostatik", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-elektrik-devreleri", subjectId: "tyt-fizik", name: "Elektrik Akımı ve Devreler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-manyetizma", subjectId: "tyt-fizik", name: "Manyetizma ve Mıknatıslar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-basinc-kaldirma", subjectId: "tyt-fizik", name: "Basınç ve Kaldırma Kuvveti", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-dalgalar", subjectId: "tyt-fizik", name: "Dalgalar (Yay, Su, Ses, Deprem)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "fiz-optik", subjectId: "tyt-fizik", name: "Optik (Aynalar, Kırılma, Mercekler, Renk)", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== TYT KİMYA (9 Konu) ====================
  { id: "kim-kimya-bilimi", subjectId: "tyt-kimya", name: "Kimya Bilimi ve Güvenlik Uyarıları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "kim-atom-periyodik-sistem", subjectId: "tyt-kimya", name: "Atom Yapısı ve Periyodik Sistem", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "kim-turler-arasi-etkilesimler", subjectId: "tyt-kimya", name: "Kimyasal Türler Arası Etkileşimler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "kim-maddenin-halleri", subjectId: "tyt-kimya", name: "Maddenin Halleri (Katı, Sıvı, Gaz, Plazma)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "kim-doga-ve-kimya", subjectId: "tyt-kimya", name: "Doğa ve Kimya (Çevre & Su)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "kim-temel-kanunlar-hesaplamalar", subjectId: "tyt-kimya", name: "Kimyanın Temel Kanunları ve Mol Kavramı", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "kim-karisimlar", subjectId: "tyt-kimya", name: "Karışımlar ve Ayırma Yöntemleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "kim-asit-baz-tuz", subjectId: "tyt-kimya", name: "Asitler, Bazlar ve Tuzlar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "kim-kimya-her-yerde", subjectId: "tyt-kimya", name: "Kimya Her Yerde (Temizlik, Polimer, İlaç)", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== TYT BİYOLOJİ (9 Konu) ====================
  { id: "biy-ortak-ozellikler", subjectId: "tyt-biyoloji", name: "Canlıların Ortak Özellikleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "biy-temel-bilesikler", subjectId: "tyt-biyoloji", name: "Canlıların Temel Bileşikleri (İnorganik & Organik)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "biy-hucre-ve-organeller", subjectId: "tyt-biyoloji", name: "Hücre Yapısı ve Organeller", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "biy-madde-gecisleri", subjectId: "tyt-biyoloji", name: "Hücre Zarından Madde Geçişleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "biy-siniflandirma", subjectId: "tyt-biyoloji", name: "Canlılar Dünyası ve Sınıflandırma", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "biy-mitoz-ureme", subjectId: "tyt-biyoloji", name: "Hücre Bölünmeleri (Mitoz ve Eşeysiz Üreme)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "biy-mayoz-ureme", subjectId: "tyt-biyoloji", name: "Mayoz Bölünme ve Eşeyli Üreme", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "biy-kalitim", subjectId: "tyt-biyoloji", name: "Kalıtım ve Çaprazlamalar (Mendel Genetiği)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "biy-ekosistem-ekolojisi", subjectId: "tyt-biyoloji", name: "Ekosistem Ekolojisi ve Çevre Sorunları", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== TYT SOSYAL (12 Konu) ====================
  { id: "sos-tarih-bilimi-ilk-cag", subjectId: "tyt-sosyal", name: "Tarih Bilimi ve İlk Çağ Medeniyetleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-islam-oncesi-turk-tarihi", subjectId: "tyt-sosyal", name: "İlk ve Orta Çağlarda Türk Dünyası", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-islam-tarihi-ve-turkler", subjectId: "tyt-sosyal", name: "İslam Medeniyeti ve İlk Türk İslam Devletleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-osmanli-kurulus-yukselme", subjectId: "tyt-sosyal", name: "Osmanlı Devleti Kuruluş ve Klasik Çağ", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-milli-mucadele-inkilap", subjectId: "tyt-sosyal", name: "Kurtuluş Savaşı ve Atatürk İnkılapları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-cografya-doga-insan", subjectId: "tyt-sosyal", name: "Doğa ve İnsan & Harita Bilgisi", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-cografi-konum-yer-sekilleri", subjectId: "tyt-sosyal", name: "Dünyanın Şekli, Hareketleri ve Yer Şekilleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-iklim-bilgisi", subjectId: "tyt-sosyal", name: "İklim Bilgisi (Atmosfer, Sıcaklık, Basınç)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-nufus-yerlesme", subjectId: "tyt-sosyal", name: "Nüfus, Yerleşme ve Göç", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-afetler-cevre", subjectId: "tyt-sosyal", name: "Türkiye'nin Coğrafi Konumu ve Doğal Afetler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-felsefe-temel-konulari", subjectId: "tyt-sosyal", name: "Felsefenin Alanı ve Temel Problemleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "sos-din-kulturu", subjectId: "tyt-sosyal", name: "Din Kültürü ve Ahlak Bilgisi Temel Konuları", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== AYT MATEMATİK (15 Konu) ====================
  { id: "ayt-polinomlar-carpanlara-ayirma", subjectId: "ayt-matematik", name: "Polinomlar ve Çarpanlara Ayırma", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-ikinci-dereceden-denklemler", subjectId: "ayt-matematik", name: "İkinci Dereceden Denklemler & Karmaşık Sayılar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-parabol", subjectId: "ayt-matematik", name: "Parabol (İkinci Dereceden Fonksiyonlar)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-ikinci-dereceden-esitsizlikler", subjectId: "ayt-matematik", name: "İkinci Dereceden Eşitsizlikler ve Tablolar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-trigonometri-1", subjectId: "ayt-matematik", name: "Trigonometri 1 (Birim Çember, Teoremler)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-trigonometri-2", subjectId: "ayt-matematik", name: "Trigonometri 2 (Toplam-Fark, Yarım Açı, Denklemler)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-logaritma", subjectId: "ayt-matematik", name: "Üstel Fonksiyonlar ve Logaritma", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-diziler", subjectId: "ayt-matematik", name: "Diziler (Aritmetik ve Geometrik Dizi)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-limit-sureklilik", subjectId: "ayt-matematik", name: "Limit ve Süreklilik", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-turev-alma-kurallari", subjectId: "ayt-matematik", name: "Türev Alma Kuralları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-turevin-geometrik-yorumu", subjectId: "ayt-matematik", name: "Türevin Geometrik Yorumu ve Ekstremum Noktaları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-belirsiz-integral", subjectId: "ayt-matematik", name: "Belirsiz İntegral ve Değişken Değiştirme", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-belirli-integral-alan", subjectId: "ayt-matematik", name: "Belirli İntegral ve Alan Hesabı", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-sayma-olasilik-binom", subjectId: "ayt-matematik", name: "Sayma, İleri Olasılık ve Binom Açılımı", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fonksiyon-oteleme-simetri", subjectId: "ayt-matematik", name: "Fonksiyonlarda Uygulamalar ve Grafikler", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== AYT FİZİK (15 Konu) ====================
  { id: "ayt-fiz-vektorler-bagil-hareket", subjectId: "ayt-fizik", name: "Vektörler ve Bağıl Hareket", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-newton-yasalari", subjectId: "ayt-fizik", name: "Newton'ın Hareket Yasaları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-atışlar", subjectId: "ayt-fizik", name: "Bir ve İki Boyutta Sabit İvmeli Hareket (Atışlar)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-is-guc-enerji", subjectId: "ayt-fizik", name: "İş, Güç ve Enerji Dönüşümleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-itme-momentum", subjectId: "ayt-fizik", name: "İtme ve Çizgisel Momentum Korunumu", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-tork-denge-kutle", subjectId: "ayt-fizik", name: "Tork, Denge ve Kütle Merkezi", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-basit-makineler", subjectId: "ayt-fizik", name: "Basit Makineler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-elektriksel-kuvvet-alan", subjectId: "ayt-fizik", name: "Elektriksel Kuvvet, Alan ve Potansiyel", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-manyetizma-induksiyon", subjectId: "ayt-fizik", name: "Manyetizma ve Elektromanyetik İndüksiyon", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-alternatif-akim", subjectId: "ayt-fizik", name: "Alternatif Akım ve Transformatörler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-cembersel-hareket", subjectId: "ayt-fizik", name: "Düzgün Çembersel Hareket ve Dönme Kinetiği", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-basit-harmonik-hareket", subjectId: "ayt-fizik", name: "Basit Harmonik Hareket", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-dalga-mekanigi", subjectId: "ayt-fizik", name: "Dalga Mekaniği (Girişim, Kırınım, Doppler)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-atom-fizigi-radyoaktivite", subjectId: "ayt-fizik", name: "Atom Modelleri ve Radyoaktivite", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-fiz-modern-fizik", subjectId: "ayt-fizik", name: "Özel Görelilik, Foton ve Modern Fizik", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== AYT KİMYA (12 Konu) ====================
  { id: "ayt-kim-modern-atom", subjectId: "ayt-kimya", name: "Modern Atom Teorisi ve Kuantum Sayıları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-gazlar", subjectId: "ayt-kimya", name: "Gazlar ve Gaz Yasaları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-sivi-cozeltiler", subjectId: "ayt-kimya", name: "Sıvı Çözeltiler ve Koligatif Özellikler", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-entalpi", subjectId: "ayt-kimya", name: "Kimyasal Tepkimelerde Enerji (Entalpi)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-tepkime-hizi", subjectId: "ayt-kimya", name: "Kimyasal Tepkimelerde Hız", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-kimyasal-denge", subjectId: "ayt-kimya", name: "Kimyasal Denge (Le Chatelier)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-asit-baz-cozunurluk-dengesi", subjectId: "ayt-kimya", name: "Sulu Çözelti Dengeleri (pH-pOH ve KÇÇ)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-elektrokimya", subjectId: "ayt-kimya", name: "Kimya ve Elektrik (Piller, Elektroliz)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-karbon-kimyasina-giris", subjectId: "ayt-kimya", name: "Karbon Kimyasına Giriş ve Hibritleşme", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-hidrokarbonlar", subjectId: "ayt-kimya", name: "Organik Bileşikler: Hidrokarbonlar", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-fonksiyonel-gruplar", subjectId: "ayt-kimya", name: "Alkoller, Eterler ve Karbonil Bileşikleri", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-kim-karboksilik-asitler-esterler", subjectId: "ayt-kimya", name: "Karboksilik Asitler, Esterler ve Enerji Kaynakları", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== AYT BİYOLOJİ (13 Konu) ====================
  { id: "ayt-biy-sinir-sistemi", subjectId: "ayt-biyoloji", name: "Sinir Sistemi ve Duyu Organları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-endokrin-sistem", subjectId: "ayt-biyoloji", name: "Endokrin Sistem (Hormonlar)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-destek-hareket", subjectId: "ayt-biyoloji", name: "Destek ve Hareket Sistemi (Kemik, Kas)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-sindirim-sistemi", subjectId: "ayt-biyoloji", name: "Sindirim Sistemi ve Emilim", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-dolasim-bagisiklik", subjectId: "ayt-biyoloji", name: "Dolaşım ve Bağışıklık Sistemi", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-solunum-sistemi", subjectId: "ayt-biyoloji", name: "Solunum Sistemi ve Gaz Değişimi", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-uriner-sistem", subjectId: "ayt-biyoloji", name: "Boşaltım (Üriner) Sistemi", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-ureme-embriyonik", subjectId: "ayt-biyoloji", name: "Üreme Sistemi ve Embriyonik Gelişim", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-komunite-populasyon", subjectId: "ayt-biyoloji", name: "Komünite ve Popülasyon Ekolojisi", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-nukleik-asitler-protein", subjectId: "ayt-biyoloji", name: "Nükleik Asitler, Genetik Şifre ve Protein Sentezi", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-fotosentez-kemosentez", subjectId: "ayt-biyoloji", name: "Fotosentez ve Kemosentez", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-hucresel-solunum", subjectId: "ayt-biyoloji", name: "Hücresel Solunum ve Fermantasyon", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-biy-bitki-biyolojisi", subjectId: "ayt-biyoloji", name: "Bitki Biyolojisi (Doku, Taşıma, Üreme)", completed: 0, total: 5, progress: 0, status: "not_started" },

  // ==================== AYT EDEBİYAT (11 Konu) ====================
  { id: "ayt-edb-edebiyat-siir-bilgisi", subjectId: "ayt-edebiyat", name: "Şiir Bilgisi (Ölçü, Kafiye, Nazım Biçimleri)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-edebi-sanatlar", subjectId: "ayt-edebiyat", name: "Edebi Sanatlar (Teşbih, İstiare, Mecaz vb.)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-islamiyet-oncesi-gecis", subjectId: "ayt-edebiyat", name: "İslamiyet Öncesi ve Geçiş Dönemi Edebiyatı", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-halk-edebiyati", subjectId: "ayt-edebiyat", name: "Halk Edebiyatı (Anonim, Âşık, Tekke)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-divan-edebiyati", subjectId: "ayt-edebiyat", name: "Divan Edebiyatı (Şairler, Nazım Türleri)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-edebi-akimlar", subjectId: "ayt-edebiyat", name: "Batı Edebiyatı Akımları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-tanzimat-edebiyati", subjectId: "ayt-edebiyat", name: "Tanzimat Dönemi Türk Edebiyatı (1. ve 2. Dönem)", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-servetifunun-fecriati", subjectId: "ayt-edebiyat", name: "Servet-i Fünun ve Fecr-i Âti Edebiyatı", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-milli-edebiyat", subjectId: "ayt-edebiyat", name: "Milli Edebiyat Dönemi", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-cumhuriyet-siir", subjectId: "ayt-edebiyat", name: "Cumhuriyet Döneminde Şiir Toplulukları", completed: 0, total: 5, progress: 0, status: "not_started" },
  { id: "ayt-edb-cumhuriyet-roman-tiyatro", subjectId: "ayt-edebiyat", name: "Cumhuriyet Döneminde Roman, Hikâye ve Tiyatro", completed: 0, total: 5, progress: 0, status: "not_started" },
];

// For backwards compatibility
export const mathTopics = allTopics;

export const exams: Exam[] = [];

export const mistakes: MistakeRecord[] = [];
