"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { z } from "zod";
import { createClient } from "@/lib/supabase/client";
import { appConfig } from "@/lib/config";

const credentialsSchema = z.object({ email:z.string().email("Geçerli bir e-posta adresi gir."), password:z.string().min(8,"Şifre en az 8 karakter olmalı.") });
export function AuthForm({ mode }: { mode:"login"|"register" }) { const router = useRouter(); const [email,setEmail] = useState(""); const [password,setPassword] = useState(""); const [error,setError] = useState(""); const [message,setMessage] = useState(""); const [loading,setLoading] = useState(false); const configured = Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY); const isLogin = mode === "login";
  async function submit(event:React.FormEvent) { event.preventDefault(); setError(""); setMessage(""); const parsed = credentialsSchema.safeParse({email,password}); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Bilgileri kontrol et."); return; } if (!configured) { setError("Supabase bağlantısı henüz yapılandırılmadı."); return; } setLoading(true); const supabase = createClient(); const result = isLogin ? await supabase.auth.signInWithPassword(parsed.data) : await supabase.auth.signUp({ email:parsed.data.email, password:parsed.data.password, options:{ emailRedirectTo:`${window.location.origin}/auth/callback` } }); setLoading(false); if (result.error) { setError(result.error.message); return; } setMessage(isLogin ? "Giriş başarılı. Yönlendiriliyorsun..." : "Kaydı tamamlamak için e-posta adresini doğrula."); if (isLogin) router.push("/today"); }
  return <main className="flex min-h-screen items-center justify-center bg-[var(--background)] p-5"><section className="w-full max-w-md paper-card p-6 md:p-8"><Link href="/" className="font-display text-2xl font-semibold text-[var(--primary)]">{appConfig.name}</Link><h1 className="mt-8 font-display text-3xl font-semibold">{isLogin ? "Tekrar hoş geldin" : "Çalışma alanını oluştur"}</h1><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{isLogin ? "Planına kaldığın yerden devam et." : "Kişisel YKS çalışma sistemini kurmaya başla."}</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-medium">E-posta</span><input type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="app-focus h-12 w-full rounded-lg border border-[var(--outline)] px-3 outline-none focus:border-[var(--primary)]"/></label><label className="block"><span className="mb-1.5 block text-sm font-medium">Şifre</span><input type="password" autoComplete={isLogin ? "current-password" : "new-password"} required minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} className="app-focus h-12 w-full rounded-lg border border-[var(--outline)] px-3 outline-none focus:border-[var(--primary)]"/></label>{error && <p role="alert" className="text-sm text-[var(--danger)]">{error}</p>}{message && <p role="status" className="text-sm text-[var(--primary)]">{message}</p>}<button disabled={loading} className="app-focus min-h-12 w-full rounded-lg bg-[var(--primary)] text-sm font-medium text-white disabled:cursor-wait disabled:opacity-60">{loading ? "Bekleyin..." : isLogin ? "Giriş yap" : "Kayıt ol"}</button></form><p className="mt-6 text-center text-sm text-[var(--muted)]">{isLogin ? "Hesabın yok mu?" : "Zaten hesabın var mı?"} <Link className="font-medium text-[var(--primary)] underline" href={isLogin ? "/register" : "/login"}>{isLogin ? "Kayıt ol" : "Giriş yap"}</Link></p></section></main>; }
